[package]
name = "pseg-sieve"
version = "0.1.0"
authors = ["Calvin Yong"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
clap = "2.33.3"
